// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFHMfKLkYe7jwlVhmApk2tqDWwQ4_sicg',
    appId: '1:151634418522:web:ed68dd8b7b8f59ea727163',
    messagingSenderId: '151634418522',
    projectId: 'auth-hitsapp',
    authDomain: 'auth-hitsapp.firebaseapp.com',
    storageBucket: 'auth-hitsapp.firebasestorage.app',
    measurementId: 'G-ZLL1V00YJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArsAjb6LYRHCIFACXMIgfiNkbTFfYOIS4',
    appId: '1:151634418522:android:2bb0ee93c8054efe727163',
    messagingSenderId: '151634418522',
    projectId: 'auth-hitsapp',
    storageBucket: 'auth-hitsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcjDv_7tuDIpZRCuW-qetdgCNIrlokd8',
    appId: '1:151634418522:ios:e5799c67e839c6f1727163',
    messagingSenderId: '151634418522',
    projectId: 'auth-hitsapp',
    storageBucket: 'auth-hitsapp.firebasestorage.app',
    iosBundleId: 'com.example.mmcmHits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcjDv_7tuDIpZRCuW-qetdgCNIrlokd8',
    appId: '1:151634418522:ios:e5799c67e839c6f1727163',
    messagingSenderId: '151634418522',
    projectId: 'auth-hitsapp',
    storageBucket: 'auth-hitsapp.firebasestorage.app',
    iosBundleId: 'com.example.mmcmHits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFHMfKLkYe7jwlVhmApk2tqDWwQ4_sicg',
    appId: '1:151634418522:web:f1054f9361aa1937727163',
    messagingSenderId: '151634418522',
    projectId: 'auth-hitsapp',
    authDomain: 'auth-hitsapp.firebaseapp.com',
    storageBucket: 'auth-hitsapp.firebasestorage.app',
    measurementId: 'G-7LH12FJKTX',
  );
}
